Default: &defaults
  user: freedomc
  password: freedomc
  host: localhost
  port: 5432
  database: freedomc
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: freedomc_test
  <<: *defaults

Staging:
  database: freedomc_staging
  poolsize: 100
  <<: *defaults

Production:
  database: freedomc_production
  poolsize: 100
  <<: *defaults
