Default: &defaults
  database: freedomc.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: freedomc_test.sqlite3
  <<: *defaults

Staging:
  database: freedomc_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: freedomc_production.sqlite3
  poolsize: 100
  <<: *defaults
